package com.slytechs.jnet.protocol.api.descriptor;

import java.util.EnumSet;

/**
 * Packet flags using pure single-bit design.
 * All flags use individual bits (no multi-bit fields) for cleaner operations and
 * context reuse across runtime, capabilities, and emulation contexts.
 * 
 * Bit layout is designed to align with DPDK mbuf flag semantics where possible,
 * but uses single bits instead of multi-bit fields for tunnel types and L4 checksums.
 */
public enum PacketFlag {
	// ========== RX FLAGS (bits 0-20) ==========
	PACKET_FLAG_RX_VLAN(Constants.PACKET_FLAG_RX_VLAN),
	PACKET_FLAG_RX_RSS_HASH(Constants.PACKET_FLAG_RX_RSS_HASH),
	PACKET_FLAG_RX_FDIR(Constants.PACKET_FLAG_RX_FDIR),
	PACKET_FLAG_RX_L4_CKSUM_BAD(Constants.PACKET_FLAG_RX_L4_CKSUM_BAD),
	PACKET_FLAG_RX_IP_CKSUM_BAD(Constants.PACKET_FLAG_RX_IP_CKSUM_BAD),
	PACKET_FLAG_RX_OUTER_IP_CKSUM_BAD(Constants.PACKET_FLAG_RX_OUTER_IP_CKSUM_BAD),
	PACKET_FLAG_RX_VLAN_STRIPPED(Constants.PACKET_FLAG_RX_VLAN_STRIPPED),
	PACKET_FLAG_RX_IP_CKSUM_GOOD(Constants.PACKET_FLAG_RX_IP_CKSUM_GOOD),
	PACKET_FLAG_RX_L4_CKSUM_GOOD(Constants.PACKET_FLAG_RX_L4_CKSUM_GOOD),
	PACKET_FLAG_RX_IEEE1588_PTP(Constants.PACKET_FLAG_RX_IEEE1588_PTP),
	PACKET_FLAG_RX_IEEE1588_TMST(Constants.PACKET_FLAG_RX_IEEE1588_TMST),
	PACKET_FLAG_RX_FCS(Constants.PACKET_FLAG_RX_FCS),
	PACKET_FLAG_RX_OUTER_L4_CKSUM_BAD(Constants.PACKET_FLAG_RX_OUTER_L4_CKSUM_BAD),
	PACKET_FLAG_RX_OUTER_L4_CKSUM_GOOD(Constants.PACKET_FLAG_RX_OUTER_L4_CKSUM_GOOD),
	PACKET_FLAG_RX_FDIR_ID(Constants.PACKET_FLAG_RX_FDIR_ID),
	PACKET_FLAG_RX_QINQ_STRIPPED(Constants.PACKET_FLAG_RX_QINQ_STRIPPED),
	PACKET_FLAG_RX_LRO(Constants.PACKET_FLAG_RX_LRO),
	PACKET_FLAG_RX_SEC_OFFLOAD(Constants.PACKET_FLAG_RX_SEC_OFFLOAD),
	PACKET_FLAG_RX_SEC_OFFLOAD_FAILED(Constants.PACKET_FLAG_RX_SEC_OFFLOAD_FAILED),
	PACKET_FLAG_RX_MACSEC_STRIPPED(Constants.PACKET_FLAG_RX_MACSEC_STRIPPED),
	PACKET_FLAG_RX_QINQ(Constants.PACKET_FLAG_RX_QINQ),
	
	// ========== TX PROTOCOL/VERSION FLAGS (bits 32-37) ==========
	PACKET_FLAG_TX_IPV4(Constants.PACKET_FLAG_TX_IPV4),
	PACKET_FLAG_TX_IPV6(Constants.PACKET_FLAG_TX_IPV6),
	PACKET_FLAG_TX_OUTER_IP_CKSUM(Constants.PACKET_FLAG_TX_OUTER_IP_CKSUM),
	PACKET_FLAG_TX_OUTER_UDP_CKSUM(Constants.PACKET_FLAG_TX_OUTER_UDP_CKSUM),
	PACKET_FLAG_TX_OUTER_IPV4(Constants.PACKET_FLAG_TX_OUTER_IPV4),
	PACKET_FLAG_TX_OUTER_IPV6(Constants.PACKET_FLAG_TX_OUTER_IPV6),
	
	// ========== TX TUNNEL FLAGS (bits 43-52) - Individual bits ==========
	PACKET_FLAG_TX_TUNNEL_VXLAN(Constants.PACKET_FLAG_TX_TUNNEL_VXLAN),
	PACKET_FLAG_TX_TUNNEL_GRE(Constants.PACKET_FLAG_TX_TUNNEL_GRE),
	PACKET_FLAG_TX_TUNNEL_IPIP(Constants.PACKET_FLAG_TX_TUNNEL_IPIP),
	PACKET_FLAG_TX_TUNNEL_GENEVE(Constants.PACKET_FLAG_TX_TUNNEL_GENEVE),
	PACKET_FLAG_TX_TUNNEL_MPLSOUDP(Constants.PACKET_FLAG_TX_TUNNEL_MPLSOUDP),
	PACKET_FLAG_TX_TUNNEL_VXLAN_GPE(Constants.PACKET_FLAG_TX_TUNNEL_VXLAN_GPE),
	PACKET_FLAG_TX_TUNNEL_GTP(Constants.PACKET_FLAG_TX_TUNNEL_GTP),
	PACKET_FLAG_TX_TUNNEL_ESP(Constants.PACKET_FLAG_TX_TUNNEL_ESP),
	PACKET_FLAG_TX_TUNNEL_L2TP(Constants.PACKET_FLAG_TX_TUNNEL_L2TP),
	PACKET_FLAG_TX_TUNNEL_UDP(Constants.PACKET_FLAG_TX_TUNNEL_UDP),
	
	// ========== TX OFFLOAD FLAGS (bits 53-63) ==========
	PACKET_FLAG_TX_MACSEC(Constants.PACKET_FLAG_TX_MACSEC),
	PACKET_FLAG_TX_SEC_OFFLOAD(Constants.PACKET_FLAG_TX_SEC_OFFLOAD),
	PACKET_FLAG_TX_QINQ(Constants.PACKET_FLAG_TX_QINQ),
	PACKET_FLAG_TX_TCP_SEG(Constants.PACKET_FLAG_TX_TCP_SEG),
	PACKET_FLAG_TX_UDP_SEG(Constants.PACKET_FLAG_TX_UDP_SEG),
	PACKET_FLAG_TX_IEEE1588_TMST(Constants.PACKET_FLAG_TX_IEEE1588_TMST),
	PACKET_FLAG_TX_TCP_CKSUM(Constants.PACKET_FLAG_TX_TCP_CKSUM),
	PACKET_FLAG_TX_SCTP_CKSUM(Constants.PACKET_FLAG_TX_SCTP_CKSUM),
	PACKET_FLAG_TX_UDP_CKSUM(Constants.PACKET_FLAG_TX_UDP_CKSUM),
	PACKET_FLAG_TX_IP_CKSUM(Constants.PACKET_FLAG_TX_IP_CKSUM),
	PACKET_FLAG_TX_VLAN(Constants.PACKET_FLAG_TX_VLAN);

	private final long value;

	PacketFlag(long value) {
		this.value = value;
	}

	public long getValue() {
		return value;
	}

	public boolean isSet(long flags) {
		return (flags & value) != 0;
	}

	public static EnumSet<PacketFlag> asEnumSet(long flags) {
		EnumSet<PacketFlag> set = EnumSet.noneOf(PacketFlag.class);
		for (var f : values()) {
			if (f.isSet(flags))
				set.add(f);
		}
		return set;
	}

	public static long toFlags(PacketFlag... flags) {
		long result = 0;
		for (var f : flags)
			result |= f.value;
		return result;
	}

	public static long toFlags(long... flags) {
		long result = 0;
		for (var f : flags)
			result |= f;
		return result;
	}

	public interface Constants {
		// ========== RX FLAGS (bits 0-20) ==========
		long PACKET_FLAG_RX_VLAN = 1L << 0;
		long PACKET_FLAG_RX_RSS_HASH = 1L << 1;
		long PACKET_FLAG_RX_FDIR = 1L << 2;
		long PACKET_FLAG_RX_L4_CKSUM_BAD = 1L << 3;
		long PACKET_FLAG_RX_IP_CKSUM_BAD = 1L << 4;
		long PACKET_FLAG_RX_OUTER_IP_CKSUM_BAD = 1L << 5;
		long PACKET_FLAG_RX_VLAN_STRIPPED = 1L << 6;
		long PACKET_FLAG_RX_IP_CKSUM_GOOD = 1L << 7;
		long PACKET_FLAG_RX_L4_CKSUM_GOOD = 1L << 8;
		long PACKET_FLAG_RX_IEEE1588_PTP = 1L << 9;
		long PACKET_FLAG_RX_IEEE1588_TMST = 1L << 10;
		long PACKET_FLAG_RX_FCS = 1L << 11;
		long PACKET_FLAG_RX_OUTER_L4_CKSUM_BAD = 1L << 12;
		long PACKET_FLAG_RX_OUTER_L4_CKSUM_GOOD = 1L << 13;
		long PACKET_FLAG_RX_FDIR_ID = 1L << 14;
		long PACKET_FLAG_RX_QINQ_STRIPPED = 1L << 15;
		long PACKET_FLAG_RX_LRO = 1L << 16;
		long PACKET_FLAG_RX_SEC_OFFLOAD = 1L << 17;
		long PACKET_FLAG_RX_SEC_OFFLOAD_FAILED = 1L << 18;
		long PACKET_FLAG_RX_MACSEC_STRIPPED = 1L << 19;
		long PACKET_FLAG_RX_QINQ = 1L << 20;
		
		// ========== RESERVED FOR PROTOCOL DETECTION (bits 21-31) ==========
		// Available for future use: HAS_TCP, HAS_UDP, HAS_ICMP, etc.
		
		// ========== TX PROTOCOL/VERSION FLAGS (bits 32-37) ==========
		long PACKET_FLAG_TX_IPV4 = 1L << 32;
		long PACKET_FLAG_TX_IPV6 = 1L << 33;
		long PACKET_FLAG_TX_OUTER_IP_CKSUM = 1L << 34;
		long PACKET_FLAG_TX_OUTER_UDP_CKSUM = 1L << 35;
		long PACKET_FLAG_TX_OUTER_IPV4 = 1L << 36;
		long PACKET_FLAG_TX_OUTER_IPV6 = 1L << 37;
		
		// ========== RESERVED (bits 38-42) ==========
		// Available for future expansion
		
		// ========== TX TUNNEL FLAGS (bits 43-52) - Individual bits ==========
		long PACKET_FLAG_TX_TUNNEL_VXLAN = 1L << 43;
		long PACKET_FLAG_TX_TUNNEL_GRE = 1L << 44;
		long PACKET_FLAG_TX_TUNNEL_IPIP = 1L << 45;
		long PACKET_FLAG_TX_TUNNEL_GENEVE = 1L << 46;
		long PACKET_FLAG_TX_TUNNEL_MPLSOUDP = 1L << 47;
		long PACKET_FLAG_TX_TUNNEL_VXLAN_GPE = 1L << 48;
		long PACKET_FLAG_TX_TUNNEL_GTP = 1L << 49;
		long PACKET_FLAG_TX_TUNNEL_ESP = 1L << 50;
		long PACKET_FLAG_TX_TUNNEL_L2TP = 1L << 51;
		long PACKET_FLAG_TX_TUNNEL_UDP = 1L << 52;
		
		// ========== TX OFFLOAD FLAGS (bits 53-63) ==========
		long PACKET_FLAG_TX_MACSEC = 1L << 53;
		long PACKET_FLAG_TX_SEC_OFFLOAD = 1L << 54;
		long PACKET_FLAG_TX_QINQ = 1L << 55;
		long PACKET_FLAG_TX_TCP_SEG = 1L << 56;
		long PACKET_FLAG_TX_UDP_SEG = 1L << 57;
		long PACKET_FLAG_TX_IEEE1588_TMST = 1L << 58;
		long PACKET_FLAG_TX_TCP_CKSUM = 1L << 59;
		long PACKET_FLAG_TX_SCTP_CKSUM = 1L << 60;
		long PACKET_FLAG_TX_UDP_CKSUM = 1L << 61;
		long PACKET_FLAG_TX_IP_CKSUM = 1L << 62;
		long PACKET_FLAG_TX_VLAN = 1L << 63;
		
		// ========== CONVENIENCE MASKS ==========
		long PACKET_FLAG_MASK_RX_IP_CKSUM = PACKET_FLAG_RX_IP_CKSUM_BAD | PACKET_FLAG_RX_IP_CKSUM_GOOD;
		long PACKET_FLAG_MASK_RX_L4_CKSUM = PACKET_FLAG_RX_L4_CKSUM_BAD | PACKET_FLAG_RX_L4_CKSUM_GOOD;
		long PACKET_FLAG_MASK_RX_OUTER_L4_CKSUM = PACKET_FLAG_RX_OUTER_L4_CKSUM_BAD | PACKET_FLAG_RX_OUTER_L4_CKSUM_GOOD;
		
		long PACKET_FLAG_MASK_ALL_GOOD = PACKET_FLAG_RX_IP_CKSUM_GOOD
				| PACKET_FLAG_RX_L4_CKSUM_GOOD
				| PACKET_FLAG_RX_OUTER_L4_CKSUM_GOOD;

		long PACKET_FLAG_MASK_ALL_BAD = PACKET_FLAG_RX_IP_CKSUM_BAD
				| PACKET_FLAG_RX_L4_CKSUM_BAD
				| PACKET_FLAG_RX_OUTER_IP_CKSUM_BAD
				| PACKET_FLAG_RX_OUTER_L4_CKSUM_BAD;

		long PACKET_FLAG_MASK_ALL_FAILED = PACKET_FLAG_RX_SEC_OFFLOAD_FAILED;
		
		long PACKET_FLAG_MASK_TX_TUNNELS = PACKET_FLAG_TX_TUNNEL_VXLAN
				| PACKET_FLAG_TX_TUNNEL_GRE
				| PACKET_FLAG_TX_TUNNEL_IPIP
				| PACKET_FLAG_TX_TUNNEL_GENEVE
				| PACKET_FLAG_TX_TUNNEL_MPLSOUDP
				| PACKET_FLAG_TX_TUNNEL_VXLAN_GPE
				| PACKET_FLAG_TX_TUNNEL_GTP
				| PACKET_FLAG_TX_TUNNEL_ESP
				| PACKET_FLAG_TX_TUNNEL_L2TP
				| PACKET_FLAG_TX_TUNNEL_UDP;
		
		long PACKET_FLAG_MASK_TX_L4_CKSUM = PACKET_FLAG_TX_TCP_CKSUM
				| PACKET_FLAG_TX_SCTP_CKSUM
				| PACKET_FLAG_TX_UDP_CKSUM;
	}
}