package com.slytechs.jnet.protocol.api.descriptor;

public enum PacketFlag {
	PKT_RX_VLAN(Constants.PKT_RX_VLAN),
	PKT_RX_RSS_HASH(Constants.PKT_RX_RSS_HASH),
	PKT_RX_FDIR(Constants.PKT_RX_FDIR),
	PKT_RX_L4_CKSUM_BAD(Constants.PKT_RX_L4_CKSUM_BAD),
	PKT_RX_IP_CKSUM_BAD(Constants.PKT_RX_IP_CKSUM_BAD),
	PKT_RX_OUTER_IP_CKSUM_BAD(Constants.PKT_RX_OUTER_IP_CKSUM_BAD),
	PKT_RX_VLAN_STRIPPED(Constants.PKT_RX_VLAN_STRIPPED),
	PKT_RX_IP_CKSUM_GOOD(Constants.PKT_RX_IP_CKSUM_GOOD),
	PKT_RX_L4_CKSUM_GOOD(Constants.PKT_RX_L4_CKSUM_GOOD),
	PKT_RX_IEEE1588_PTP(Constants.PKT_RX_IEEE1588_PTP),
	PKT_RX_IEEE1588_TMST(Constants.PKT_RX_IEEE1588_TMST),
	PKT_RX_FCS(Constants.PKT_RX_FCS),
	PKT_RX_OUTER_L4_CKSUM_BAD(Constants.PKT_RX_OUTER_L4_CKSUM_BAD),
	PKT_RX_OUTER_L4_CKSUM_GOOD(Constants.PKT_RX_OUTER_L4_CKSUM_GOOD),
	PKT_RX_FDIR_ID(Constants.PKT_RX_FDIR_ID),
	PKT_RX_QINQ_STRIPPED(Constants.PKT_RX_QINQ_STRIPPED),
	PKT_RX_LRO(Constants.PKT_RX_LRO),
	PKT_RX_SEC_OFFLOAD(Constants.PKT_RX_SEC_OFFLOAD),
	PKT_RX_SEC_OFFLOAD_FAILED(Constants.PKT_RX_SEC_OFFLOAD_FAILED),
	PKT_RX_MACSEC_STRIPPED(Constants.PKT_RX_MACSEC_STRIPPED),
	PKT_RX_QINQ(Constants.PKT_RX_QINQ),
	PKT_TX_MACSEC(Constants.PKT_TX_MACSEC),
	PKT_TX_SEC_OFFLOAD(Constants.PKT_TX_SEC_OFFLOAD),
	PKT_TX_TUNNEL_VXLAN(Constants.PKT_TX_TUNNEL_VXLAN),
	PKT_TX_TUNNEL_GRE(Constants.PKT_TX_TUNNEL_GRE),
	PKT_TX_TUNNEL_IP(Constants.PKT_TX_TUNNEL_IP),
	PKT_TX_TUNNEL_IPINIP(Constants.PKT_TX_TUNNEL_IPINIP),
	PKT_TX_TUNNEL_GENEVE(Constants.PKT_TX_TUNNEL_GENEVE),
	PKT_TX_TUNNEL_MPLSOUDP(Constants.PKT_TX_TUNNEL_MPLSOUDP),
	PKT_TX_TUNNEL_VXLAN_GPE(Constants.PKT_TX_TUNNEL_VXLAN_GPE),
	PKT_TX_TUNNEL_GTP(Constants.PKT_TX_TUNNEL_GTP),
	PKT_TX_TUNNEL_ESP(Constants.PKT_TX_TUNNEL_ESP),
	PKT_TX_TUNNEL_L2TP(Constants.PKT_TX_TUNNEL_L2TP),
	PKT_TX_TUNNEL_IPIP(Constants.PKT_TX_TUNNEL_IPIP),
	PKT_TX_TUNNEL_UDP(Constants.PKT_TX_TUNNEL_UDP),
	PKT_TX_QINQ(Constants.PKT_TX_QINQ),
	PKT_TX_TCP_SEG(Constants.PKT_TX_TCP_SEG),
	PKT_TX_IEEE1588_TMST(Constants.PKT_TX_IEEE1588_TMST),
	PKT_TX_TCP_CKSUM(Constants.PKT_TX_TCP_CKSUM),
	PKT_TX_SCTP_CKSUM(Constants.PKT_TX_SCTP_CKSUM),
	PKT_TX_UDP_CKSUM(Constants.PKT_TX_UDP_CKSUM),
	PKT_TX_IP_CKSUM(Constants.PKT_TX_IP_CKSUM),
	PKT_TX_IPV4(Constants.PKT_TX_IPV4),
	PKT_TX_IPV6(Constants.PKT_TX_IPV6),
	PKT_TX_VLAN(Constants.PKT_TX_VLAN),
	PKT_TX_OUTER_IP_CKSUM(Constants.PKT_TX_OUTER_IP_CKSUM),
	PKT_TX_OUTER_UDP_CKSUM(Constants.PKT_TX_OUTER_UDP_CKSUM),
	PKT_TX_OUTER_IPV4(Constants.PKT_TX_OUTER_IPV4),
	PKT_TX_OUTER_IPV6(Constants.PKT_TX_OUTER_IPV6),
	PKT_TX_UDP_SEG(Constants.PKT_TX_UDP_SEG);

	private final long value;

	PacketFlag(long value) {
		this.value = value;
	}

	public long getValue() {
		return value;
	}

	public interface Constants {
		long PKT_RX_VLAN = 1L << 0;
		long PKT_RX_RSS_HASH = 1L << 1;
		long PKT_RX_FDIR = 1L << 2;
		long PKT_RX_L4_CKSUM_BAD = 1L << 3;
		long PKT_RX_IP_CKSUM_BAD = 1L << 4;
		long PKT_RX_OUTER_IP_CKSUM_BAD = 1L << 5;
		long PKT_RX_VLAN_STRIPPED = 1L << 6;
		long PKT_RX_IP_CKSUM_GOOD = 1L << 7;
		long PKT_RX_L4_CKSUM_GOOD = 1L << 8;
		long PKT_RX_IEEE1588_PTP = 1L << 9;
		long PKT_RX_IEEE1588_TMST = 1L << 10;
		long PKT_RX_FCS = 1L << 11;
		long PKT_RX_OUTER_L4_CKSUM_BAD = 1L << 12;
		long PKT_RX_OUTER_L4_CKSUM_GOOD = 1L << 13;
		long PKT_RX_FDIR_ID = 1L << 14;
		long PKT_RX_QINQ_STRIPPED = 1L << 15;
		long PKT_RX_LRO = 1L << 16;
		long PKT_RX_SEC_OFFLOAD = 1L << 17;
		long PKT_RX_SEC_OFFLOAD_FAILED = 1L << 18;
		long PKT_RX_MACSEC_STRIPPED = 1L << 19;
		long PKT_RX_QINQ = 1L << 20;
		long PKT_RX_IP_CKSUM_MASK = (1L << 4) | (1L << 7);
		long PKT_RX_L4_CKSUM_MASK = (1L << 3) | (1L << 8);
		long PKT_RX_OUTER_L4_CKSUM_MASK = (1L << 12) | (1L << 13);
		long PKT_TX_MACSEC = 1L << 43;
		long PKT_TX_SEC_OFFLOAD = 1L << 44;
		long PKT_TX_TUNNEL_VXLAN = 1L << 45;
		long PKT_TX_TUNNEL_GRE = 2L << 45;
		long PKT_TX_TUNNEL_IP = 3L << 45;
		long PKT_TX_TUNNEL_IPINIP = 4L << 45;
		long PKT_TX_TUNNEL_GENEVE = 5L << 45;
		long PKT_TX_TUNNEL_MPLSOUDP = 6L << 45;
		long PKT_TX_TUNNEL_VXLAN_GPE = 7L << 45;
		long PKT_TX_TUNNEL_GTP = 8L << 45;
		long PKT_TX_TUNNEL_ESP = 9L << 45;
		long PKT_TX_TUNNEL_L2TP = 10L << 45;
		long PKT_TX_TUNNEL_IPIP = 11L << 45;
		long PKT_TX_TUNNEL_UDP = 12L << 45;
		long PKT_TX_TUNNEL_MASK = 0xFL << 45;
		long PKT_TX_QINQ = 1L << 49;
		long PKT_TX_TCP_SEG = 1L << 50;
		long PKT_TX_IEEE1588_TMST = 1L << 51;
		long PKT_TX_TCP_CKSUM = 1L << 52;
		long PKT_TX_SCTP_CKSUM = 2L << 52;
		long PKT_TX_UDP_CKSUM = 3L << 52;
		long PKT_TX_L4_MASK = 3L << 52;
		long PKT_TX_L4_NO_CKSUM = 0L << 52;
		long PKT_TX_IP_CKSUM = 1L << 54;
		long PKT_TX_IPV4 = 1L << 55;
		long PKT_TX_IPV6 = 1L << 56;
		long PKT_TX_VLAN = 1L << 57;
		long PKT_TX_OUTER_IP_CKSUM = 1L << 58;
		long PKT_TX_OUTER_UDP_CKSUM = 1L << 59;
		long PKT_TX_OUTER_IPV4 = 1L << 60;
		long PKT_TX_OUTER_IPV6 = 1L << 61;
		long PKT_TX_UDP_SEG = 1L << 62;

		long PKT_MASK_ALL_GOOD = Constants.PKT_RX_IP_CKSUM_GOOD
				| Constants.PKT_RX_L4_CKSUM_GOOD
				| Constants.PKT_RX_OUTER_L4_CKSUM_GOOD;

		long PKT_MASK_ALL_BAD = Constants.PKT_RX_IP_CKSUM_BAD
				| Constants.PKT_RX_L4_CKSUM_BAD
				| Constants.PKT_RX_OUTER_IP_CKSUM_BAD
				| Constants.PKT_RX_OUTER_L4_CKSUM_BAD;

		long PKT_MASK_ALL_FAILED = Constants.PKT_RX_SEC_OFFLOAD_FAILED;
	}
}