package com.slytechs.jnet.protocol.api.builder;

import com.slytechs.jnet.core.api.time.TimestampUnit;
import com.slytechs.jnet.protocol.api.Header;
import com.slytechs.jnet.protocol.api.Packet;
import com.slytechs.jnet.protocol.api.PacketDirection;
import com.slytechs.jnet.protocol.api.descriptor.NetTag;

public interface PacketBuilder {
    PacketBuilder withCaptureLength(int length);
    PacketBuilder withWireLength(int length);
    PacketBuilder withTimestamp(long timestamp);
    PacketBuilder usingTimestampUnit(int unit);
    PacketBuilder usingTimestampUnitEnum(TimestampUnit unit);
    PacketBuilder withPacketFlagBitmask(long flags);
    PacketBuilder withPacketType(long type);
    PacketBuilder withL2Offset(int offset);
    PacketBuilder withL3Offset(int offset);
    PacketBuilder withL4Offset(int offset);
    PacketBuilder withL2OffsetOuter(int offset);
    PacketBuilder withL3OffsetOuter(int offset);
    PacketBuilder withL2OffsetInner(int offset);
    PacketBuilder withL3OffsetInner(int offset);
    PacketBuilder withL4OffsetInner(int offset);
    PacketBuilder withL2Length(int length);
    PacketBuilder withL3Length(int length);
    PacketBuilder withL4Length(int length);
    PacketBuilder withL2LengthOuter(int length);
    PacketBuilder withL3LengthOuter(int length);
    PacketBuilder withL2LengthInner(int length);
    PacketBuilder withL3LengthInner(int length);
    PacketBuilder withL4LengthInner(int length);
    PacketBuilder withVlanTci(int tci);
    PacketBuilder withVlanTciOuter(int tci);
    PacketBuilder withHash(long hash);
    PacketBuilder usingHashType(int type);
//    PacketBuilder usingHashTypeEnum(HashType type);
    PacketBuilder withFlowId(long id);
    PacketBuilder withTsoSegmentSize(int size);
    PacketBuilder onPort(int port);
    PacketBuilder usingDirection(int direction);
    PacketBuilder usingDirectionEnum(PacketDirection direction);
    PacketBuilder withUserData(long data);
    PacketBuilder withTxEnabled(boolean enabled);
    PacketBuilder withTxImmediate(boolean immediate);
    PacketBuilder withTxSyncTimestamp(boolean sync);
    PacketBuilder withTxTimestamp(long timestamp);
    PacketBuilder onTxPort(int port);
    PacketBuilder withTxOffsetInjection(int offset);
    PacketBuilder withTxIpChecksumAtOffset(int offset);
    PacketBuilder withTxL4ChecksumAtOffset(int offset);
    PacketBuilder addTagChain(NetTag tag);
//    PacketBuilder addLayer(ProtocolStackLayer layer, Object... args);
    PacketBuilder modifyHeader(Header header, Object... fields);
//    PacketBuilder withData(Mbuf dataChain);
    PacketBuilder injectData(int offset, byte[] data);
    Packet build();
    void modify(Packet packet);
}